version: '3.7'
services:
    nginx:
      container_name: nginx
      image: nginx:alpine
      ports:
        - target: 80
          published: 80
          protocol: tcp
      volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      depends_on:
        - frontend

    frontend:
      container_name: frontend
      image: mrlucienjohnson/spring-petclinic-angular:latest
      build: ./spring-petclinic-angular
      ports:
        - target: 8080
          published: 8080
  
    backend:
      container_name: backend
      image: springcommunity/spring-petclinic-rest:latest
      #build: ./spring-petclinic-rest
      ports:
        - target: 9966
          published: 9966