apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer  # set the type of Service
  selector:
    app: nginx     # referencing the Pod's label
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config    
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        location / {
            proxy_pass http://frontend:8080;
        }
        location /petclinic/api/ {
          proxy_pass http://backend:9966/petclinic/api/;
      }
    }